#!/bin/sh

case "$1" in
    mirror)
        xrandr --output eDP1 --mode 1920x1080 --pos 0x0 --auto --output HDMI1 --mode 1920x1080 --pos 0x0 --primary --auto
        ;;
    work-both)
        xrandr --output HDMI1 --primary --auto --mode 1920x1080 --output eDP1 --auto --below HDMI1
        ;;
    work-external)
        xrandr --output HDMI1 --primary --auto --mode 1920x1080 --output eDP1 --off
        ;;
    home-both)
        xrandr --output HDMI1 --primary --auto --output eDP1 --auto --below HDMI1
        ;;
    home-external)
        xrandr --output HDMI1 --primary --auto --output eDP1 --off
        ;;
    laptop-only)
        xrandr --fb 1920x1080 --output eDP1 --primary --mode 1920x1080 --auto --output HDMI1 --off
        ;;
    *)
        exit 2
esac
