theme = "snazzy"

[editor]
auto-format = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
C-s = ":w"
G = "goto_file_end"
D = "@t<ret>d"
V = ["extend_line_below", "select_mode"]
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection"]

[keys.select]
V = ["extend_line_below"]

[keys.insert]
C-s = [":w", "normal_mode"]

[keys.normal."space"."space"]
c = ":buffer-close"
q = ":q"
k = ":buffer-previous"
j = ":buffer-next"
o = ":config-open"
r = ":config-reload"
