theme = "snazzy"

[editor]
auto-format = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
C-s = ":w"
C-h = "goto_next_buffer"
C-l = "goto_previous_buffer"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"C-]" = "goto_definition"
G = "goto_file_end"
D = "@t<ret>d"
V = ["extend_line_below", "select_mode"]

[keys.normal.g]
"]" = "goto_definition"

[keys.select]
V = ["extend_line_below"]
G = "extend_to_file_end"

[keys.insert]
C-s = [":w", "normal_mode"]

[keys.normal."space"."space"]
w = ":write"
d = ":buffer-close"
q = ":q"
k = ":buffer-previous"
j = ":buffer-next"
c = ":config-open"
r = ":config-reload"
